Set-ItemProperty 'HKLM:\SOFTWARE\Policies\Microsoft\Windows Defender' DisableAntiSpyware 0

Set-MpPreference -AllowDatagramProcessingOnWinServer $false
Set-MpPreference -AllowNetworkProtectionDownLevel $false
Set-MpPreference -AllowNetworkProtectionOnWinServer $false
Set-MpPreference -CheckForSignaturesBeforeRunningScan $true
Set-MpPreference -CloudBlockLevel 2
Set-MpPreference -CloudExtendedTimeout 8
Set-MpPreference -DisableArchiveScanning $false
Set-MpPreference -DisableAutoExclusions $false
Set-MpPreference -DisableBehaviorMonitoring $false
Set-MpPreference -DisableIOAVProtection $false
Set-MpPreference -DisableBlockAtFirstSeen $false
Set-MpPreference -DisableCatchupFullScan $true
Set-MpPreference -DisableCatchupQuickScan $true
Set-MpPreference -DisableCpuThrottleOnIdleScans $true
Set-MpPreference -DisableDatagramProcessing $false
Set-MpPreference -DisableDnsOverTcpParsing $false
Set-MpPreference -DisableDnsParsing $false
Set-MpPreference -DisableEmailScanning $true
Set-MpPreference -DisableGradualRelease $false
Set-MpPreference -DisableHttpParsing $false
Set-MpPreference -DisableInboundConnectionFiltering $false
Set-MpPreference -DisablePrivacyMode $false
Set-MpPreference -DisableRdpParsing $false
Set-MpPreference -DisableRealtimeMonitoring $false
Set-MpPreference -DisableRemovableDriveScanning $false
Set-MpPreference -DisableRestorePoint $true
Set-MpPreference -DisableScanningMappedNetworkDrivesForFullScan $true
Set-MpPreference -DisableScanningNetworkFiles $false
Set-MpPreference -DisableScriptScanning $false
Set-MpPreference -DisableSshParsing $false
Set-MpPreference -DisableTlsParsing $false
Set-MpPreference -EnableControlledFolderAccess 2
Set-MpPreference -EnableDnsSinkhole $true
Set-MpPreference -EnableFileHashComputation $false
Set-MpPreference -EnableFullScanOnBatteryPower $false
Set-MpPreference -EnableLowCpuPriority $true
Set-MpPreference -ForceUseProxyOnly $false
Set-MpPreference -HighThreatDefaultAction 2
Set-MpPreference -LowThreatDefaultAction 2
Set-MpPreference -MAPSReporting 1
Set-MpPreference -MeteredConnectionUpdates $true
Set-MpPreference -ModerateThreatDefaultAction 2
Set-MpPreference -PUAProtection 2
Set-MpPreference -PlatformUpdatesChannel 0
Set-MpPreference -QuarantinePurgeItemsAfterDelay 30
Set-MpPreference -RandomizeScheduleTaskTimes $true
Set-MpPreference -RealTimeScanDirection 0
Set-MpPreference -ScanAvgCPULoadFactor 50
Set-MpPreference -ScanOnlyIfIdleEnabled $true
Set-MpPreference -ScanParameters 2
Set-MpPreference -ScanPurgeItemsAfterDelay 15
Set-MpPreference -SevereThreatDefaultAction 2
Set-MpPreference -SignatureAuGracePeriod 0
Set-MpPreference -SignatureBlobUpdateInterval 60
Set-MpPreference -SignatureFallbackOrder 'MicrosoftUpdateServer|MMPC'
Set-MpPreference -SignatureFirstAuGracePeriod 120
Set-MpPreference -SignatureUpdateCatchupInterval 1
Set-MpPreference -SignatureUpdateInterval 8
Set-MpPreference -SubmitSamplesConsent 1
Set-MpPreference -UILockdown $false
Set-MpPreference -UnknownThreatDefaultAction 2
Update-MpSignature
